<?php
/**
 * @file
 * MMW Charts Module file.
 *
 * @brief Main file for Drupal module.
 *
 * @package mmw_charts
 *
 * @author Makemeweb
 */

module_load_include('php', 'mmw_charts', 'classes/XLSReader');
module_load_include('inc', 'mmw_charts', 'includes/mmw_charts.ajax');
module_load_include('inc', 'mmw_charts', 'includes/mmw_charts.form');
module_load_include('inc', 'mmw_charts', 'includes/mmw_charts.data');
module_load_include('inc', 'mmw_charts', 'includes/mmw_charts.export');
module_load_include('inc', 'mmw_charts', 'includes/mmw_charts.node');

/**
 * Implements hook_libraries_info().
 */
function mmw_charts_libraries_info() {
  return array(
    'PHPExcel' => array(
      'name' => 'PHPExcel',
      'vendor url' => 'http://phpexcel.codeplex.com/',
      'download url' => 'https://github.com/PHPOffice/PHPExcel',
      'version callback' => 'mmw_charts_get_library_version',
      'path' => 'Classes',
      'files' => array(
        'php' => array(
          'PHPExcel.php',
        ),
      ),
    ),
  );
}

/**
 * Libraries API version callback.
 *
 * @return string
 *   Return version of PHPExcel, if library not exist return 'n/a'.
 */
function mmw_charts_get_library_version() {
  $library = libraries_load('PHPExcel');
  $changelog_file = $library['library path'] . '/changelog.txt';

  if (file_exists($changelog_file)) {
    $changelog = file_get_contents($changelog_file);
    $match;

    if (preg_match('/\d{4}-\d{2}-\d{2}\s+\(v([0-9\.]+)/', $changelog, $match)) {
      return $match[1];
    }
    elseif (preg_match('/@version\s+([0-9\.]+)/', $changelog, $match)) {
      return $match[1];
    }
  }

  return 'n/a';
}

/**
 * Implements hook_menu().
 */
function mmw_charts_menu() {
  $items['charts/ajax'] = array(
    'page callback' => 'mmw_charts_get_json_action',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'mmw_charts_ajax_callback',
  );
  $items['charts/export'] = array(
    'page callback' => 'mmw_charts_export_action',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function mmw_charts_theme() {
  return array(
    'node__advanced_fusioncharts' => array(
      'variables' => array(),
      'template' => 'node--advanced-fusioncharts' ,
      'base hook' => 'node',
      'path' => drupal_get_path('module', 'mmw_charts') . '/templates',
    ),
    'categories_checkbox' => array(
      'path' => drupal_get_path('module', 'mmw_charts') . '/templates',
      'template' => 'categories_checkbox',
      'variables' => array(),
    ),
    'select_countries' => array(
      'path' => drupal_get_path('module', 'mmw_charts') . '/templates',
      'template' => 'select_countries',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add custom submit for process to convert excel file to json format.
 */
function mmw_charts_form_advanced_fusioncharts_node_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'mmw_charts_converts_excel_to_json';
}

/**
 * An entity-bound allowed values callback.
 *
 * @return array
 *   An array of data type.
 */
function mmw_charts_data_type_values_callback($field, $instance, $entity_type, $entity, &$cacheable) {
  $cacheable = FALSE;
  return array('demo' => 'démographie', 'test2' => 'test2');
}
